version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/microblog
    depends_on:
      - db
    volumes:
      - ./static:/app/static

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=microblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: